# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
#---------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------------------------------------#
homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_sec
  longitude: !secret longitude_sec
  # Impacts weather/sunrise data, majorly important for circadian_lighting (altitude above sea level in meters)
  elevation: !secret elevation_sec
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  allowlist_external_dirs:
    - /documentaries
    - /movies
    - /tv_shows
    - /ssl
#---------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------------------------------------#

automation: !include_dir_merge_list automations/
group: !include groups.yaml
light: !include lights.yaml
notify: !include notify.yaml
panel_iframe: !include panel_iframe.yaml
script: !include_dir_merge_list scripts/
sensor: !include_dir_merge_list sensor/
switch: !include_dir_merge_list switch/
zone: !include zone.yaml


###SYSTEM##################################################################################

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Discover some devices automatically
discovery:

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

folder_watcher:
  - folder: /documentaries
    patterns:
      - '*.mp4'
      - '*.mkv'
  - folder: /movies
    patterns:
      - '*.mp4'
      - '*.mkv'
  - folder: /tv_shows
    patterns:
      - '*.mp4'
      - '*.mkv'

frontend:
# Add themes
  themes: !include themes.yaml

gdacs:
  categories:
    - Drought
    - Earthquake
    - Flood
    - Tropical Cyclone
    - Tsunami
    - Volcano
  radius: 1000
  latitude: !secret latitude_sec
  longitude: !secret longitude_sec

geo_location:
  - platform: usgs_earthquakes_feed
    entity_namespace: 'usgs_earthquakes_service_feed'
    feed_type: 'past_month_all_earthquakes'
    radius: 100
    minimum_magnitude: 0.0
  - platform: nsw_rural_fire_service_feed
    entity_namespace: 'nsw_fire_service_feed'
    radius: 100

# View all events in a logbook
logbook:

logger:
  default: info
  logs:
    custom_components.circadian_lighting: info
    custom_components.circadian_lighting.sensor: info
    custom_components.circadian_lighting.switch: info

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

system_health:

# Text to speech
tts:
  - platform: google_translate

zeroconf:

#---------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------------------------------------#

### USER ADDONS #####################################################################################

###Anniversaries/Countdowns/Tracking###

anniversaries:
  sensors:
  - name: Our Wedding Anniversary
    date: !secret anniversary_wedding
  - name: Grandpa - Memorial
    date: !secret memorial_gp_rew
  - name: Papaw - Memorial
    date: !secret memorial_gp_jlh
  - name: Gerald - Memorial
    date: !secret memorial_gp_e_gs
  - name: Robby's Work Anniversary
    date: !secret anniversary_work_rob

binary_sensor:
  - platform: iss
    show_on_map: true
  - platform: aurora

camera:
  - platform: generic
    still_image_url: !secret weathermap1
    name: !secret weathermapname1
  - platform: generic
    still_image_url: !secret weathermap2
    name: !secret weathermapname2

circadian_lighting:
  interval: 600
  max_colortemp: 10000
  min_colortemp: 2000

device_tracker:
  - platform: icloud3
    username: !secret icloud_un
    password: !secret icloud_password
    track_devices:
      - !secret icloud_1
      - !secret icloud_2
      - !secret icloud_3
      - !secret icloud_4
      - !secret icloud_5
      - !secret icloud_6
      - !secret icloud_7
      - !secret icloud_9
      - !secret icloud_10
    tracking_method: fmf

garbage_collection:
  sensors:
  - name: "waste"
    frequency: "weekly"
    collection_days: "tue"
    verbose_state: true

homekit:
  safe_mode: false
  filter:
   exclude_domains:
     - light
     - device_tracker
     - sensor

hue:
  bridges:
    - host: !secret host_hue
      allow_unreachable: false
      allow_hue_groups: true

icloud:
  - username: !secret icloud_un
    password: !secret icloud_password

influxdb:
  host: !secret host_unraid_influx
  port: 8086
  database: home_assistant
  max_retries: 3
  measurement_attr: entity_id
  include:
    domains:
      - sensor

ios:

plex:
  host: !secret host_unraid
  port: 32400
  token: !secret plex_token
  ssl: false
  verify_ssl: false
  media_player:
    use_episode_art: true
    show_all_controls: true

vacuum:
 - platform: roomba
   host: !secret host_roomba
   username: !secret roomba_blid
   password: !secret roomba_password

weather:
 - platform: darksky
   api_key: !secret darksky_password
   latitude: !secret latitude_sec
   longitude: !secret longitude_sec
