- platform: group
  name: Dining Room Hutch_Group
  entities:
    - light.dining_room_hutch_left
    - light.dining_room_hutch_right
    
- platform: group
  name: Great Room
  entities:
    - light.great_room_lamp

- platform: group
  name: Master Bedroom_Group
  entities:
    - light.master_bedroom_emilys_lamp
    - light.master_bedroom_robbys_lamp
    
- platform: group
  name: Weston's Room
  entities:
    - light.westons_room_lamp