### SERVER #############################################


# Sensor to monitor the status of deluge
  - platform: deluge
    host: !secret host_syno
    username: !secret deluge_un
    password: !secret deluge_password
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'


# Sensor to monitor my GutHub repo
  - platform: github
    access_token: !secret github_api
    repositories:
      - path: 'robertomano24/home-assistant'


# Sensor to monitor my Synology system
  - platform: synologydsm
    host: !secret host_syno
    username: !secret synology_un
    password: !secret synology_password
    monitored_conditions:
      - cpu_total_load
      - memory_real_usage
      - network_up
      - network_down
      - disk_temp
      - volume_percentage_used
