
#Sensor for custom_component discord_game - track friend status in specific server via Discord Bot
  - platform: discord_game
    token: !secret discord_token_bot2
    members:
      - !secret discord_un_1
      - !secret discord_un_2
      - !secret discord_un_3
      - !secret discord_un_4
      - !secret discord_un_5
      - !secret discord_un_6
      - !secret discord_un_7


#Sensor for Steam - track friend status
  - platform: steam_online
    api_key: !secret steam_api
    accounts:
      - !secret steam_id64_1
      - !secret steam_id64_2
      - !secret steam_id64_3
      - !secret steam_id64_4
      - !secret steam_id64_5
      - !secret steam_id64_6
      - !secret steam_id64_7
      - !secret steam_id64_8


#Sebsir for XBOX Live - track friend status
  - platform: xbox_live
    api_key: !secret xbox_api
    xuid:
      - !secret xbox_id_1
