### WEATHER ################################################################################

#DarkSky Sensor
  - platform: darksky
    api_key: !secret darksky_password
    scan_interval: '00:05:00'
    monitored_conditions:
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed


#WeatherAlerts sensors for important counties
  - platform: weatheralerts
    sameid: !secret county_1


  - platform: weatheralerts
    sameid: !secret county_2


#WeatherAlert Count Sensor
  - platform: rest
    resource: https://api.weather.gov/alerts/active/count
    name: NWS Alert Count
    value_template: >
      {% if value_json.zones.OHZ070 is defined %}
        {{ value_json.zones.OHZ070 }}
      {% elif value_json.zones.OHC017 is defined %}
        {{ value_json.zones.OHC017 }}
      {% else %}
        0
      {% endif %}
    #json_attributes:
    #  - event
    #  - description
    #  - instructions
    #  - expires
    headers:
      User-Agent: Homeassistant
      Accept: application/ld+json
    scan_interval: 60

  - platform: rest
    resource: !secret weather_1
    name: NWS Alert Event
    value_template: >
      {% if value_json.features[0] is defined %}
        {{ value_json['features'][0]['properties'].event }}
      {% else %}
        None
      {% endif %}
    json_attributes:
      - features
    #  - description
    #  - instructions
    #  - expires
    headers:
      User-Agent: Homeassistant
      Accept: application/geo+json
    scan_interval: 60
