# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_sec
  longitude: !secret longitude_sec
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation_sec
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml

#GitHub Ready!
###SYSTEM##################################################################################

breaking_changes:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Discover some devices automatically
discovery:

folder_watcher:
  - folder: /config/media
  
frontend:
  # Add themes
  themes: !include themes.yaml
  # Enable ES6 features
  javascript_version: latest

geo_location:
  - platform: usgs_earthquakes_feed
    entity_namespace: 'usgs_earthquakes_service_feed'
    feed_type: 'past_month_all_earthquakes'
    radius: 2500
    minimum_magnitude: 0.0
  - platform: nsw_rural_fire_service_feed
    entity_namespace: 'nsw_fire_service_feed'
    radius: 2500
    
hacs:
  token: !secret hacs_token
  theme: true
  python_script: true
  
# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

logger:
  default: error
  logs:
    custom_components.circadian_lighting: debug
    custom_components.circadian_lighting.sensor: debug
    custom_components.circadian_lighting.switch: debug

# Enables a map showing the location of tracked devices
map:

mqtt:
  broker: !secret host_syno
mqtt_eventstream:
  publish_topic: master/topic
  subscribe_topic: slaves/#
  
# Track the sun
sun:

system_health:

# Text to speech
tts:
  - platform: google_translate

zeroconf:

###USER ADDONS###############################################################################################

camera:
  - platform: synology
    url: !secret host_syno5001
    username: !secret synology_un
    password: !secret synology_password
    timeout: 15
    verify_ssl: false
  - platform: nwsradar
    station: ILN
    style: Enhanced
    frames: 8

circadian_lighting:
  interval: 600
  max_colortemp: 10000
  min_colortemp: 2000

device_tracker:
  - platform: icloud3
    username: !secret icloud_un
    password: !secret icloud_password
    account_name: !secret icloud_descriptive_name
    include_device_type: iphone
    sensor_name_prefix:
      - robertwhitesiphone @ R
      - iphone_2 @ E
      
  - platform: iphonedetect
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false
    hosts:
      hostname1: !secret host_iphonerw
       
ecobee:
  api_key: !secret ecobee_password

google:
  client_id: !secret google_client
  client_secret: !secret google_secret
  
homekit:
  safe_mode: true
  filter:
   exclude_domains:
     - light 
     - device_tracker

hue:
  bridges:
    - host: !secret host_hue
      allow_unreachable: false
      allow_hue_groups: true
           
input_boolean:
  dummy_switch:

light:
  - platform: decora_wifi
    username: !secret decora_un
    password: !secret decora_password
  
lutron_caseta:
    host: !secret host_lutron
    keyfile: caseta.key
    certfile: caseta.crt
    ca_certs: caseta-bridge.crt
    
plex:
  host: !secret host_syno
  port: 32400
  token: !secret plex_token
  ssl: false
  verify_ssl: false
  media_player:
    use_episode_art: true
    show_all_controls: true
    
notify:
# Adding support for Discord notifications via The Best Server (Channel ID: saved in secrets)
  - platform: discord
    token: !secret discord_token
# Adding support for notifications to the Ecobee
  - name: ecobee_main
    platform: ecobee
# Adding support for notifications for Alexa
  - platform: alexa_media
    name: alexa_media

openuv:
  api_key: !secret openuv_api
  binary_sensors:
    monitored_conditions:
      - uv_protection_window
  sensors:
    monitored_conditions:
      - current_ozone_level
      - current_uv_index
      - current_uv_level
      - max_uv_index
      - safe_exposure_time_type_1
      - safe_exposure_time_type_2
      - safe_exposure_time_type_3
      - safe_exposure_time_type_4
      - safe_exposure_time_type_5
      - safe_exposure_time_type_6
  
pi_hole:
  host: !secret host_pi_hole
  ssl: false
  verify_ssl: false

speedtestdotnet:
  scan_interval:
    minutes: 60
  monitored_conditions:
    - ping
    - download
    - upload
  
vacuum:
 - platform: roomba
   host: !secret host_roomba
   username: !secret roomba_un
   password: !secret roomba_password
    
weather:
  - platform: darksky
    api_key: !secret darksky_password
    latitude: !secret latitude_sec
    longitude: !secret longitude_sec

wink: