# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_sec
  longitude: !secret longitude_sec
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation_sec
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml

#GitHub Ready!
###SYSTEM##################################################################################

breaking_changes:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Discover some devices automatically
discovery:

#folder_watcher:
#  - folder: /config
#    patterns:
#      - '*.mp4'
#      - '*.mkv'

frontend:
  # Add themes
  themes: !include themes.yaml
  # Enable ES6 features
  javascript_version: latest

geo_location:
  - platform: usgs_earthquakes_feed
    entity_namespace: 'usgs_earthquakes_service_feed'
    feed_type: 'past_month_all_earthquakes'
    radius: 100
    minimum_magnitude: 0.0
  - platform: nsw_rural_fire_service_feed
    entity_namespace: 'nsw_fire_service_feed'
    radius: 100

hacs:
  token: !secret hacs_token
  theme: true
  python_script: true

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

logger:
  default: error
  logs:
    custom_components.circadian_lighting: debug
    custom_components.circadian_lighting.sensor: debug
    custom_components.circadian_lighting.switch: debug

# Enables a map showing the location of tracked devices
map:

mqtt:
  broker: !secret host_syno
mqtt_eventstream:
  publish_topic: master/topic
  subscribe_topic: slaves/#

# Track the sun
sun:

system_health:

# Text to speech
tts:
  - platform: google_translate

zeroconf:

###USER ADDONS###############################################################################################

binary_sensor:
  - platform: iss
    show_on_map: true
camera:
  - platform: synology
    url: !secret host_syno5001
    username: !secret synology_un
    password: !secret synology_password
    timeout: 15
    verify_ssl: false
  - platform: nwsradar
    station: ILN
    style: Enhanced
    frames: 8

circadian_lighting:
  interval: 600
  max_colortemp: 10000
  min_colortemp: 2000

device_tracker:
  - platform: icloud3
    username: !secret icloud_un
    password: !secret icloud_password
    group: family
    track_devices:
      - !secret icloud_1
      - !secret icloud_2
      - !secret icloud_3
      - !secret icloud_4
      - !secret icloud_5
      - !secret icloud_6
      - !secret icloud_7
      - !secret icloud_8
      - !secret icloud_9
      - !secret icloud_10

  - platform: iphonedetect
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false
    hosts:
      hostname1: !secret host_iphonerw

ecobee:
  api_key: !secret ecobee_api

fastdotcom:
  scan_interval:
      minutes: 30

freedns:
  access_token: !secret freedns_token

garbage_collection:
  sensors:
  - name: "waste"
    frequency: "weekly"
    collection_days: "tue"
    verbose_state: true

google:
  client_id: !secret google_client
  client_secret: !secret google_secret

homekit:
  safe_mode: false
  filter:
   exclude_domains:
     - light
     - device_tracker

hue:
  bridges:
    - host: !secret host_hue
      allow_unreachable: false
      allow_hue_groups: true

input_boolean:
  dummy_switch:

input_select:
  destination:
    name: destination
    options:
      - Home
      - Parents

influxdb:
  host: !secret host_syno_influx
  database: home_assistant

light:
  - platform: decora_wifi
    username: !secret decora_un
    password: !secret decora_password

lutron_caseta:
    host: !secret host_lutron
    keyfile: caseta.key
    certfile: caseta.crt
    ca_certs: caseta-bridge.crt

media_player:
  # Use the Python ADB implementation without authentication
  - platform: androidtv
    name: Firestick
    host: !secret host_firetv

notify:
# Adding support for Discord notifications via The Best Server (Channel ID: saved in secrets)
  - platform: discord
    token: !secret discord_token
# Adding support for notifications to the Ecobee
  - name: ecobee_main
    platform: ecobee
# Adding support for notifications for Alexa
  - platform: alexa_media
    name: alexa_media
# Adding support for notifications for FireTV
  - platform: nfandroidtv
    name: Bedroom
    host: !secret host_firetv

openuv:
  api_key: !secret openuv_api
  binary_sensors:
    monitored_conditions:
      - uv_protection_window
  sensors:
    monitored_conditions:
      - current_ozone_level
      - current_uv_index
      - current_uv_level
      - max_uv_index
      - safe_exposure_time_type_1
      - safe_exposure_time_type_2
      - safe_exposure_time_type_3
      - safe_exposure_time_type_4
      - safe_exposure_time_type_5
      - safe_exposure_time_type_6

owntracks:
  max_gps_accuracy: 200
  waypoints: true
  mqtt_topic: "owntracks/#"
  events_only: true

pi_hole:
  host: !secret host_pi_hole
  ssl: false
  verify_ssl: false

plex:
  host: !secret host_syno
  port: 32400
  token: !secret plex_token
  ssl: false
  verify_ssl: false
  media_player:
    use_episode_art: true
    show_all_controls: true

speedtestdotnet:
  scan_interval:
    minutes: 60
  monitored_conditions:
    - ping
    - download
    - upload

vacuum:
 - platform: roomba
   host: !secret host_roomba
   username: !secret roomba_blid
   password: !secret roomba_password

weather:
 - platform: darksky
   api_key: !secret darksky_password
   latitude: !secret latitude_sec
   longitude: !secret longitude_sec

wink:

wunderlist:
   client_id: !secret wunderlist_client
   access_token: !secret wunderlist_token

zone:
 - name: 'Home_iBeacon'
   latitude: !secret latitude_sec
   longitude: !secret longitude_sec
   radius: 20
   icon: mdi:home

 - name: !secret location_home
   latitude: !secret latitude_sec
   longitude: !secret longitude_sec
   radius: 20
   icon: mdi:home

 - name: !secret location_fam_1
   latitude: !secret latitude_fam_1
   longitude: !secret longitude_fam_1
   radius: 20
   icon: mdi:home

 - name: !secret location_friends_1
   latitude: !secret latitude_friends_1
   longitude: !secret longitude_friends_1
   radius: 20
   icon: mdi:home-circle-outline

 - name: !secret location_friends_2
   latitude: !secret latitude_friends_2
   longitude: !secret longitude_friends_2
   radius: 20
   icon: mdi:home-circle-outline

 - name: !secret location_grandparents_r_1
   latitude: !secret latitude_grandparents_r_1
   longitude: !secret longitude_grandparents_r_1
   radius: 25
   icon: mdi:home-circle-outline

 - name: !secret location_grandparents_r_2
   latitude: !secret latitude_grandparents_r_2
   longitude: !secret longitude_grandparents_r_2
   radius: 25
   icon: mdi:home-circle-outline

 - name: !secret location_lib
   latitude: !secret latitude_lib
   longitude: !secret longitude_lib
   radius: 275
   icon: mdi:city-variant-outline

 - name: !secret location_mvh
   latitude: !secret latitude_mvh
   longitude: !secret longitude_mvh
   radius: 200
   icon: mdi:hospital-building

 - name: !secret location_parents_e
   latitude: !secret latitude_parents_e
   longitude: !secret longitude_parents_e
   radius: 20
   icon: mdi:home-circle-outline

 - name: !secret location_parents_r
   latitude: !secret latitude_parents_r
   longitude: !secret longitude_parents_r
   radius: 50
   icon: mdi:home-circle-outline
 - name: !secret location_parents_r
   latitude: !secret latitude_parents_r_other
   longitude: !secret longitude_parents_r_other
   radius: 50

 - name: !secret location_parents_rental
   latitude: !secret latitude_parents_rental
   longitude: !secret longitude_parents_rental
   radius: 25
   icon: mdi:home-circle-outline

 - name: !secret location_work2
   latitude: !secret latitude_work2
   longitude: !secret longitude_work2
   radius: 100
   icon: mdi:bus-school

 - name: !secret location_work_dad
   latitude: !secret latitude_work_dad
   longitude: !secret longitude_work_dad
   radius: 100
   icon: mdi:antenna

 - name: !secret location_work_mom_1
   latitude: !secret latitude_work_mom_1
   longitude: !secret longitude_work_mom_1
   radius: 150
   icon: mdi:school

 - name: !secret location_misc_cl
   latitude: !secret latitude_misc_cl
   longitude: !secret longitude_misc_cl
   radius: 350
   icon: mdi:campfire

 - name: !secret location_church2
   latitude: !secret latitude_church2
   longitude: !secret longitude_church2
   radius: 100
   icon: mdi:church
