# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
logger: debug

ssl_cert: ...fullchain.pem
ssl_key: ...privkey.pem

#Passwords, Tokens, and APIs
airvisual_api: api-key
co2_api: api-key
darksky_password: password
decora_password: password
deluge_password: password
discord_token: token
discord_token_bot2: token
duckdns_token: token
duke_password: password
ecobee_api: api-key
fedex_password: password
freedns_token: token
github_api: api-key
google_places_api: api-key
google_secret: secret
google_2_secret: secret
gpodder_password: password
grafana_api: api-key==
hacs_token: token
icloud_password: password
lutron_password: password
openuv_api: api-key
pc_password: password
plex_token: token
radarr_api: api-key
roomba_password: password-blid
sonarr_api: api-key
steam_api: api-key
synology_password: password
todoist_api: api-key
ups_password: password
wunderlist_token: token
xbox_api: api-key
zillow_api: api-key

#usernames/clients
decora_un: xxxxx@gmail.com
deluge_un: user
discord_un_1: user
discord_un_2: user
discord_un_3: user
discord_un_4: user
discord_un_5: user
discord_un_6: user
discord_un_7: user
duke_un: user
fedex_un: user
google_client: user.apps.googleusercontent.com
google_2_client: user.apps.googleusercontent.com
gpodder_un: user
icloud_un: xxxxx@aol.com
lutron_un: xxxxx@gmail.com
pc_un: xxxxx@gmail.com
roomba_blid: 000000000000
steam_id64_1: 00000000000
steam_id64_2: 00000000000
steam_id64_3: 00000000000
steam_id64_4: 00000000000
steam_id64_5: 00000000000
steam_id64_6: 00000000000
steam_id64_7: 00000000000
steam_id64_8: 00000000000
###https://steamid.io
##
synology_un: user
ups_un: user
wunderlist_client: client_id

#hosts
host_domain_duckdns: https://xxxxxxxxxxx.duckdns.org:8123
host_syno: 0.0.0.0
host_syno1880: 0.0.0.0
host_syno5001: https://0.0.0.0
host_syno_influx: 0.0.0.0
host_ubuntu: 0.0.0.0
host_pi_hole: 0.0.0.0
host_roomba: 0.0.0.0
host_iphonerw: 0.0.0.0
host_firetv: 0.0.0.0
host_hue: 0.0.0.0
host_lutron: 0.0.0.0

#Location Data
latitude_sec: 00.000000
longitude_sec: 00.000000
elevation_sec: 00.00
county_1: '000000'
county_2: '000000'
weather_1: https://api.weather.gov/alerts/active?zone=ST0000,ST0000


latitude_church2: 00.000000
longitude_church2: 00.000000
latitude_fam_1: 00.000000
longitude_fam_1: 00.000000
latitude_friends_1: 00.000000
longitude_friends_1: 00.000000
latitude_friends_2: 00.000000
longitude_friends_2: 00.000000
latitude_grandparents_r_1: 00.000000
longitude_grandparents_r_1: 00.000000
latitude_grandparents_r_2: 00.000000
longitude_grandparents_r_2: 00.000000
latitude_gym: 00.000000
longitude_gym: 00.000000
latitude_lib: 00.000000
longitude_lib: 00.000000
latitude_misc_cl: 00.000000
longitude_misc_cl: 00.000000
latitude_mvh: 00.000000
longitude_mvh: 00.000000
latitude_parents_e: 00.000000
longitude_parents_e: 00.000000
latitude_parents_r: 00.000000
longitude_parents_r: 00.000000
latitude_parents_r_other: 00.000000
longitude_parents_r_other: 00.000000
latitude_parents_rental: 00.000000
longitude_parents_rental: 00.000000
latitude_work1: 00.000000
longitude_work1: 00.000000
latitude_work2: 00.000000
longitude_work2: 00.000000
latitude_work3: 00.000000
longitude_work3: 00.000000
latitude_work_dad: 00.000000
longitude_work_dad: 00.000000
latitude_work_mom_1: 00.000000
longitude_work_mom_1: 00.000000

#locations: Addresses and Names
location_church2: place
location_city_home: place
location_city_home_north: place
location_city_home_south: place
location_fam_1: place
location_friends_1: place
location_friends_2: place
location_grandparents_r_1: place
location_grandparents_r_2: place
location_gym: place
location_home: address
location_lib: place
location_lib_add: address
location_misc_cl: place
location_mvh: place
location_add_parents_r: address
location_parents_e: place
location_parents_r: place
location_parents_rental: place
location_work1: place
location_work1_add: address
location_work2: place
location_work3: place
location_work3_add: address
location_work_dad: place
location_work_mom_1: place

# Links/URLs
freedns_url: https://url
podcast1_url: 'https://url'

# Descriptive information
icloud_descriptive_name: description
podcast1_name: description

### Calendar IDs
cal_id_1: cal_id
# Holidays
cal_id_2: cal_id
# Main Calendar
cal_id_3: cal_id
cal_id_4: cal_id
# Todois Calendar
cal_id_5: cal_id
# CDNA Calendar
cal_id_6: cal_id
cal_id_7: cal_id

#Device IDs
device_id_1: device_id

#icloud
icloud_1: someones_iphone > someone@someone.com, /local/pictures/someone.png
icloud_2: someones_iphone > someone@someone.com, /local/pictures/someone.png
icloud_3: someones_iphone > someone@someone.com, /local/pictures/someone.png
icloud_4: someones_iphone > someone@someone.com, /local/pictures/someone.png
icloud_5: someones_iphone > someone@someone.com, /local/pictures/someone.png
icloud_6: someones_iphone > someone@someone.com, /local/pictures/someone.png
icloud_7: someones_iphone > someone@someone.com, /local/pictures/someone.png
icloud_8: someones_iphone > someone@someone.com, /local/pictures/someone.png
icloud_9: someones_iphone > someone@someone.com, /local/pictures/someone.png
icloud_10: someones_iphone > someone@someone.com, /local/pictures/someone.png

dev1_pic: /local/pictures/someone.png
dev2_pic: /local/pictures/someone.png
dev3_pic: /local/pictures/someone.png
dev4_pic: /local/pictures/someone.png
dev5_pic: /local/pictures/someone.png
dev6_pic: /local/pictures/someone.png
dev7_pic: /local/pictures/someone.png
dev8_pic: /local/pictures/someone.png
dev9_pic: /local/pictures/someone.png
dev10_pic: /local/pictures/someone.png

#Personal
zpid_current_home: zpid
name_wh_1: name
name_wh_2: name
iphone_1: someonesiphone

###The Best Server Channel ID For Discord Notify###
discord_channel_id: channel_id
discord_notify_media: 'channel_id'

###Grafana
grafana_server: 'http://io=p/d/key/server?orgId=1'
grafana_temp: 'http://ip/d/key/home?orgId=1&panelId=2&fullscreen'
Grafana_temp_cmd: "curl -s -H 'Authorization: Bearer bearer_token==' http://ip/render/d-solo/key/home?orgId=1&panelId=2&width=1000&height=500&tz=America%2FNew_York > /local/downloads/home_temperature.png"
grafana_weather: 'http://ip/d/key/weather?orgId=1'
grafana_temp_cam: http://ip/render/d-solo/key/home?orgId=1&panelId=2&width=1000&height=500&tz=America%2FNew_York
grafana_unifi_poller_wan: http://ip/d/key/unifi-poller-usg-insights?orgId=1&refresh=30s&var-Site=All&var-host=All&panelId=3&fullscreen

#####XBOX UIDs
xbox_id_1: 0000000000000000000

#anniversaries
anniversary_wedding: 0000-00-00
memorial_gp_rew: 0000-00-00
memorial_gp_jlh: 0000-00-00
memorial_gp_e_gs: 0000-00-00

#####Welcome
welcome_brandon: Welcome to the House, Brandon.
welcome_e: Welcome to the Home, Emily.
welcome_r: Welcome to the Home, Robby.
welcome_samuel: Welcome to the House, Samuel.
