### SYSTEM ####################################################

  - platform: version
    name: HA Installed Version
    scan_interval: 86400

  - platform: command_line
    name: "HA Uptime"
    command: echo "$(($(date +%s) - $(date -d "$(head -n1 /config/home-assistant.log | cut -d' ' -f-2)" +%s)))"
    scan_interval: 720
    value_template: >-
      {% set uptime = value | int %}
      {% set seconds = uptime % 60 %}
      {% set minutes = ((uptime % 3600) / 60) | int %}
      {% set hours = ((uptime % 86400) / 3600) | int %}
      {% set days = (uptime / 86400) | int %}
      {%- if days > 0 -%}
        {%- if days == 1 -%}
          1 day
        {%- else -%}
          {{ days }} days
        {%- endif -%}
        {{ ', ' }}
      {%- endif -%}
      {%- if hours > 0 -%}
        {%- if hours == 1 -%}
          1 hour
        {%- else -%}
          {{ hours }} hours
        {%- endif -%}
        {{ ', ' }}
      {%- endif -%}
      {%- if minutes > 0 -%}
        {%- if minutes == 1 -%}
          1 minute
        {%- else -%}
          {{ minutes }} minutes
        {%- endif -%}
      {%- endif -%}

### SERVER #############################################

  - platform: deluge
    host: !secret host_syno
    username: !secret deulge_un
    password: !secret deluge_password
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'

  - platform: github
    access_token: !secret github_api
    repositories:
      - path: 'robertomano24/home-assistant'

  - platform: synologydsm
    host: !secret host_syno
    username: whitehouse
    password: !secret synology_password
    monitored_conditions:
      - cpu_total_load
      - memory_real_usage
      - network_up
      - network_down
      - disk_temp
      - volume_percentage_used

### Anniversaries #############################################

  - platform: anniversaries
    name: White Wedding
    date: '2015-07-18'

  - platform: anniversaries
    name: Grandpa's Passing
    date: '2010-07-30'

  - platform: anniversaries
    name: Papa's Passing
    date: '2010-03-27'

  - platform: anniversaries
    name: Gerald's Passing
    date: '2019-01-13'

### DELIVERIES #############################################

  - platform: fedex
    username: !secret fedex_un
    password: !secret fedex_password

  - platform: ups
    username: !secret ups_un
    password: !secret ups_password

### ENVIRONMENT ####################################################

  - platform: co2signal
    token: !secret co2_api

  - platform: mold_indicator
    indoor_temp_sensor: sensor.main_temperature
    indoor_humidity_sensor: sensor.main_humidity
    outdoor_temp_sensor: sensor.dark_sky_temperature
    calibration_factor: 2.0

  - platform: moon

  - platform: season
    type: astronomical

### ICLOUD ####################################################

  - platform: template
    sensors:
      robert_badge:
        friendly_name: !secret name_wh_1
        value_template: '{{states.sensor.robertwhitesiphone.state}}'
        entity_picture_template: !secret pic_1
      emily_badge:
        friendly_name: !secret name_wh_2
        value_template: '{{states.sensor.iphone_2.state}}'
        entity_picture_template: !secret pic_2

### MEDIA #############################################

  - platform: plex_recently_added
    name: Recently Added Movies
    token: !secret plex_token
    host: !secret host_syno
    port: 32400
    section_types:
    - movie

  - platform: plex_recently_added
    name: Recently Added TV
    token: !secret plex_token
    host: !secret host_syno
    port: 32400
    section_types:
    - show

  - platform: radarr_upcoming_media
    api_key: !secret radarr_api
    host: !secret host_ubuntu
    port: 7878
    days: 120
    theaters: true
    max: 10

  - platform: sonarr_upcoming_media
    api_key: !secret sonarr_api
    host: !secret host_ubuntu
    port: 8989
    days: 7
    max: 10

### OTHER ################################################################################

  - platform: duke_energy
    username: !secret duke_un
    password: !secret duke_password

  - platform: zestimate
    api_key: !secret zillow_api
    zpid:
      - !secret zpid_current_home

### WAZE ################################################################################

  - platform: template
    sensors:
       dest_address:
         value_template: >-
            {%- if is_state("input_select.destination", "Home")  -%}
              !secret location_home
            {%- elif is_state("input_select.destination", "Parents")  -%}
              !secret location_parents
            {%- else -%}
              Unknown
            {%- endif %}

# Tracking entity to entity
  - platform: waze_travel_time
    name: "Me to Liberty"
    origin: device_tracker.robert_whites_iphone_ha
    destination: !secret location_liberty
    region: 'US'

  - platform: waze_travel_time
    name: "Home to Liberty"
    origin: !secret location_home
    destination: !secret location_liberty
    region: 'US'

  - platform: waze_travel_time
    name: "Home to south"
    origin: !secret location_home
    destination: !secret location_city_home_south
    region: 'US'

  - platform: waze_travel_time
    name: "Home to north"
    origin: !secret location_home
    destination: !secret location_city_home_north
    region: 'US'

### WEATHER ################################################################################

  - platform: darksky
    api_key: !secret darksky_password
    scan_interval: '00:05:00'
    monitored_conditions:
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed

  - platform: weatheralerts
    sameid: '039017'

  - platform: weatheralerts
    sameid: '039165'

  - platform: rest
    resource: https://api.weather.gov/alerts/active/count
    name: NWS Alert Count
    value_template: >
      {% if value_json.zones.OHZ070 is defined %}
        {{ value_json.zones.OHZ070 }}
      {% elif value_json.zones.OHC017 is defined %}
        {{ value_json.zones.OHC017 }}
      {% else %}
        0
      {% endif %}
    #json_attributes:
    #  - event
    #  - description
    #  - instructions
    #  - expires
    headers:
      User-Agent: Homeassistant
      Accept: application/ld+json
    scan_interval: 60

  - platform: rest
    resource: https://api.weather.gov/alerts/active?zone=OHZ070,OHC017
    name: NWS Alert Event
    value_template: >
      {% if value_json.features[0] is defined %}
        {{ value_json['features'][0]['properties'].event }}
      {% else %}
        None
      {% endif %}
    json_attributes:
      - features
    #  - description
    #  - instructions
    #  - expires
    headers:
      User-Agent: Homeassistant
      Accept: application/geo+json
    scan_interval: 60
