- alias: Doorbell_Sonos
  condition: []
  action:
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.g4_doorbell_pro_doorbell
      to: 'on'
  condition: []
  action:
    - service: media_player.play_media
      data:
        entity_id:
          - media_player.dining_room_2
          - media_player.family_room_2
          - media_player.garage_speaker
          - media_player.office_sonos_2
          - media_player.kitchen_sonos
          - media_player.upstairs_bathroom_sonos
          - media_player.uvc_g3_instant_speaker
        media_content_type: music
        media_content_id: "https://homeassistant.white.fm/local/doorbell.wav"
        extra:
          volume: 50  # Can be provided as 0-100 or 0.0-0.99
          play_on_bonded: true