#Home assistant theme is set based on location of the sun; where when sun is up, theme is light, and visa versa

- alias: 'Set HA theme for day and night'
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  action:
    - service: frontend.set_theme
      data:
        name: >
          {% if states('sun.sun') == "above_horizon" %}
            Light - Navy Blue
          {% else %}
            slate
          {% endif %}

