- alias: 'Matrix_Movies'
  trigger:
    platform: event
    event_type: folder_watcher
    event_data:
      event_type: created
  condition:
    condition: template
    value_template: '{{ "/movies" in trigger.event.data.folder }}'
  action:
    - service: notify.matrix_media
      data:
        title: HA Movie Update
        message: "Created {{ trigger.event.data.file }} in {{ trigger.event.data.folder }}"
        data:
          file: "{{ trigger.event.data.path }}"
        
- alias: 'Matrix_TV'
  trigger:
    platform: event
    event_type: folder_watcher
    event_data:
      event_type: created
  condition:
    condition: template
    value_template: '{{ "/tv_shows" in trigger.event.data.folder }}'
  action:
    - service: notify.matrix_media
      data:
        title: HA TV Update
        message: "Created {{ trigger.event.data.file }} in {{ trigger.event.data.folder }}"
        data:
          file: "{{ trigger.event.data.path }}"

- alias: 'Matrix_Documentary'
  trigger:
    platform: event
    event_type: folder_watcher
    event_data:
      event_type: created
  condition:
    condition: template
    value_template: '{{ "/documentaries" in trigger.event.data.folder }}'
  action:
    - service: notify.matrix_media
      data:
        title: HA Documentary Update
        message: "Created {{ trigger.event.data.file }} in {{ trigger.event.data.folder }}"
        data:
          file: "{{ trigger.event.data.path }}"
        
#- alias: "Face taught"
#  trigger:
##  - event_data:
 #     service: facebox.teach_face
 #   event_type: call_service
 #   platform: event
 # condition: []
 # action:
 ## - service: notify.discord
 #   data_template:
 #     message: '{{ trigger.event.data.service_data.name }} taught
 #     with file {{ trigger.event.data.service_data.file_path }}'
  #    title: Face taught notification
   #   target: !secret discord_notify_unraid


#- alias: "Facebox error"
 # trigger:
  #  platform: event
   # event_type: system_log_event
#  condition:
 #   condition: template
  #  value_template: '{{ "facebox" in trigger.event.data.message }}
#  action:
 # - service: notify.discord
  #  data_template:
   #   message: "{{ trigger.event.data.message }}"
    #  title: Facebox Error
     # target: !secret discord_notify_unraid