###Welcome Home

- alias: 'Welcome Home Robby'
  trigger:
  - entity_id: device_tracker.robert_whites_iphone_ha
    from: 'away'
    platform: state
    to: 'Home_Ibeacon'
  condition: []
  action:
  - service: script.sonos_say
    data:
      sonos_entity: media_player.living_room_speaker
      volume: 0.5
      message: !secret welcome_r


- alias: 'Welcome Home Emily'
  trigger:
  - entity_id: sensor.emily_iphone_zone_name1
    from: 'away'
    platform: state
    to: 'Home_Ibeacon'
  condition: []
  action:
  - service: script.sonos_say
    data:
      sonos_entity: media_player.living_room_speaker
      volume: 0.5
      message: !secret welcome_e


###Welcome Friends/Family

- alias: 'Welcome Brandon'
  trigger:
  - entity_id: device_tracker.brandon_farler_galaxy_s10
    from: 'away'
    platform: state
    to: 'home'
  condition: []
  action:
  - service: script.sonos_say
    data:
      sonos_entity: media_player.living_room_speaker
      volume: 0.5
      message: !secret welcome_brandon


- alias: 'Welcome Samuel'
  trigger:
  - entity_id: device_tracker.samuels_iphone
    from: 'Away'
    platform: state
    to: 'Home'
  condition: []
  action:
  - service: script.sonos_say
    data:
      sonos_entity: media_player.living_room_speaker
      volume: 0.5
      message: !secret welcome_samuel
